#### 通过协方差矩阵的特征值分解，实现PCA

In [1]:
# 创建测试数据，10个样本，4维特征
import numpy as np

X = np.random.rand(10,4)*50
# 对原样本进行demean操作
X_demean = X - np.mean(X,axis=0)
X_demean

array([[ 30.57875485,   4.20436783, -14.27598789, -20.04509528],
       [  1.53753697, -12.2702763 ,  25.60342509,   5.51601509],
       [ -8.65661849,  19.40641074, -17.876841  ,  25.13441867],
       [ 11.07467223,   9.42011905,  26.09898637,   3.27154446],
       [ -1.97244022, -18.22727899,  -5.38437776,  -3.13973552],
       [ -8.68784633, -13.55652489,  13.78966229, -21.33390753],
       [ -3.08695825,  14.00582903,  11.1570016 ,  12.2212398 ],
       [-14.40564799,  12.16896719, -11.57289556,   9.81837377],
       [  8.69124488,   0.75569886,  -9.12138984,  11.07516197],
       [-15.07269764, -15.90731252, -18.41758331, -22.51801543]])

In [2]:
# 2）计算协方差矩阵
cov = (X_demean.T.dot(X_demean)) / (len(X_demean)-1)
cov

array([[192.68386977,  25.28391089,  29.78146447, -37.53160317],
       [ 25.28391089, 194.16195093, -29.17062322, 152.2542612 ],
       [ 29.78146447, -29.17062322, 306.67130823,  13.62249776],
       [-37.53160317, 152.2542612 ,  13.62249776, 268.349691  ]])

In [3]:
# 对协方差矩阵进行特征值分解（对角化）
eigvals, eigvecs = np.linalg.eig(cov)
print(eigvals)
print(eigvecs)

[ 54.38343944 202.93568884 314.48503033 390.06266132]
[[-0.32476625  0.92257935  0.18901156 -0.08745777]
 [ 0.72748824  0.31221115  0.00874401  0.61090802]
 [ 0.15400985 -0.15540276  0.96862988 -0.11784357]
 [-0.58443881 -0.16498948  0.16110348  0.77798163]]


In [6]:
# 新的协方差矩阵
cov_new = eigvecs.T.dot(cov).dot(eigvecs)
print(cov_new)

[[ 5.43834394e+01  2.70666541e-14 -3.83814736e-14 -1.24240311e-14]
 [ 4.21762442e-14  2.02935689e+02 -3.54895552e-15  5.65949684e-14]
 [-3.68931716e-14  1.54323410e-16  3.14485030e+02 -2.78334713e-13]
 [ 2.40760173e-14  5.69425761e-14 -2.83528051e-13  3.90062661e+02]]


In [16]:
# 将特征值从大到小排列，取前3个特征值，得到降维数据
sorted_index = np.argsort(-eigvals)

X_new = X_demean.dot(eigvecs[:,sorted_index[0:3]])
print("new:",X_new)
print("cov_new:",(X_new.T.dot(X_new)) / (len(X_new)-1)) # 降维数据的协方差矩阵

new: [[-14.01825014 -11.24098197  35.04973591]
 [ -6.35632039  25.87221265  -7.30134455]
 [ 34.27340738 -14.73331112  -3.29632379]
 [  4.25586389  27.98292583   8.56270515]
 [-12.77082796  -6.25348494  -6.15572183]
 [-25.74438145   8.15947042 -10.87080718]
 [ 17.01937094  12.31488566  -2.22539276]
 [ 17.69631127 -12.24450665  -9.31253455]
 [  9.39271541  -5.40165001   7.84450464]
 [-23.74788895 -24.45555987 -12.29482104]]
cov_new: [[ 3.90062661e+02 -2.73080165e-13  5.84158087e-14]
 [-2.73080165e-13  3.14485030e+02  2.38638962e-15]
 [ 5.84158087e-14  2.38638962e-15  2.02935689e+02]]


In [19]:
# demean与数据压缩
# 选择合适的k
sorted_index = np.argsort(-eigvals)
sum_power = sum(eigvals);
cur_power = 0;
for k in range(len(eigvals)):    
    cur_power += eigvals[sorted_index[k]]    
    if cur_power / sum_power > 0.9:        
        break;

# 降维
X_new2 = X.dot(eigvecs[:,sorted_index[0:k+1]])
print(X_new2)
print('降维后的协方差矩阵：',((X_new2-np.mean(X_new2,axis=0)).T.dot(X_new2-np.mean(X_new2,axis=0))) / (len(X_new2)-1)) 

[[12.94147898 13.82202912 48.54270727]
 [20.60340873 50.93522375  6.19162681]
 [61.2331365  10.32969997 10.19664758]
 [31.21559301 53.04593692 22.05567651]
 [14.18890116 18.80952615  7.33724954]
 [ 1.21534767 33.22248152  2.62216418]
 [43.97910006 37.37789676 11.2675786 ]
 [44.65604039 12.81850444  4.18043681]
 [36.35244452 19.66136108 21.33747601]
 [ 3.21184017  0.60745122  1.19815032]]
降维后的协方差矩阵： [[ 3.90062661e+02 -2.76337653e-13  4.57839378e-14]
 [-2.76337653e-13  3.14485030e+02  2.61875269e-14]
 [ 4.57839378e-14  2.61875269e-14  2.02935689e+02]]
