#### SVD降维演示

In [1]:
# 1）创建测试用例
# 5个数据，3维特征
import numpy as np
X = np.random.randint(0,10,(5,3))
print(X)

[[3 3 2]
 [5 4 8]
 [8 2 3]
 [3 3 8]
 [0 1 4]]


In [2]:
# 2）使用协方差矩阵对角化方法对数据进行降维
# demean
X_demean = X - np.mean(X,axis=0)
# 计算协方差矩阵
cov = X_demean.T.dot(X_demean) / (len(X_demean)-1)
# 对协方差矩阵进行特征值分解（对角化）
eigvals, eigvecs = np.linalg.eig(cov)
# 新样本的协方差矩阵
cov_new = eigvecs.T.dot(cov).dot(eigvecs)
# 选择合适的k
sorted_index = np.argsort(-eigvals)
sum_power = sum(eigvals);
cur_power = 0;
for k in range(len(eigvals)):  
    cur_power += eigvals[sorted_index[k]]  
    if cur_power / sum_power > 0.9:     
        break;
# 降维
X_new = X.dot(eigvecs[:,sorted_index[0:k+1]])
print(X_new)

[[3.49894312 2.41921027]
 [5.82746772 8.3376621 ]
 [8.30929043 2.82009393]
 [3.69607273 8.24745269]
 [0.28884691 4.1129274 ]]


In [4]:
# 3）使用SVD来降维
U,Sigma,V_T = np.linalg.svd(X_demean)
print(eigvals)
print(Sigma**2 / len(X_demean)-1)

[0.6974989  8.87510672 8.42739438]
[ 6.10008538  5.7419155  -0.44200088]
