#### SVD降维演示

In [1]:
# 1）创建测试用例
# 5个数据，3维特征
import numpy as np
X = np.random.randint(0,10,(5,3))
print(X)

[[8 7 6]
 [6 2 5]
 [7 4 8]
 [7 5 8]
 [7 6 1]]


In [2]:
# 2）使用协方差矩阵对角化方法对数据进行降维
# demean
X_demean = X - np.mean(X,axis=0)
# 计算协方差矩阵
cov = X_demean.T.dot(X_demean) / (len(X_demean)-1)
# 对协方差矩阵进行特征值分解（对角化）
eigvals, eigvecs = np.linalg.eig(cov)
# 新样本的协方差矩阵
cov_new = eigvecs.T.dot(cov).dot(eigvecs)
# 选择合适的k
sorted_index = np.argsort(-eigvals)
sum_power = sum(eigvals);
cur_power = 0;
for k in range(len(eigvals)):  
    cur_power += eigvals[sorted_index[k]]  
    if cur_power / sum_power > 0.9:     
        break;

print("k:",k)
# 降维
X_new = X.dot(eigvecs[:,sorted_index[0:k+1]])
print("eigvals:",eigvals)
print("eigvecs: ", eigvecs)
print("X_new: ",X_new)

k: 1
eigvals: [0.02570456 3.92464735 8.54964809]
eigvecs:  [[-0.93721611  0.34872349 -0.00422998]
 [ 0.34088682  0.91345884 -0.22223662]
 [ 0.07363522  0.20972569  0.97498358]]
X_new:  [[ 4.26040526 10.44235399]
 [ 4.40506477  4.96788709]
 [ 6.88131229  7.77270534]
 [ 6.65907566  8.68616419]
 [-0.38804605  8.1315432 ]]


In [3]:
# 3）使用SVD来降维
U,Sigma,V_T = np.linalg.svd(X_demean)
print(Sigma**2 / (len(X_demean)-1))
print("V:", V_T.T)

[8.54964809 3.92464735 0.02570456]
V: [[ 0.00422998  0.34872349 -0.93721611]
 [ 0.22223662  0.91345884  0.34088682]
 [-0.97498358  0.20972569  0.07363522]]


In [4]:
# 选择合适的k
sorted_index = np.argsort(-Sigma)
sum_power = sum(Sigma)
cur_power = 0
for k in range(len(Sigma)):    
    cur_power += Sigma[sorted_index[k]]   
    if cur_power / sum_power > 0.9:        
        break;

print("k: ",k)

# 降维
X_new2 = X.dot(V_T.T[:,sorted_index[0:k+1]])

print(X_new) # cov矩阵的特征值分解降维结果
print(X_new2) # 样本矩阵SVD分解降维结果

k:  1
[[ 4.26040526 10.44235399]
 [ 4.40506477  4.96788709]
 [ 6.88131229  7.77270534]
 [ 6.65907566  8.68616419]
 [-0.38804605  8.1315432 ]]
[[-4.26040526 10.44235399]
 [-4.40506477  4.96788709]
 [-6.88131229  7.77270534]
 [-6.65907566  8.68616419]
 [ 0.38804605  8.1315432 ]]
