### SVM参数调整

In [5]:
# 导包
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.metrics import accuracy_score
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.colors

In [19]:
# 数据加载
data = pd.read_csv('data/svm3.txt', sep='\t', header=None)
X, y = data[[0, 1]], data[2]
print(X)
print(y)

      0    1
0   7.0  3.2
1   6.4  3.2
2   6.9  3.1
3   5.5  2.3
4   6.5  2.8
..  ...  ...
95  6.7  3.0
96  6.3  2.5
97  6.5  3.0
98  6.2  3.4
99  5.9  3.0

[100 rows x 2 columns]
0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: 2, Length: 100, dtype: int64


In [33]:
# 定义多个候选分类器
clf_params = (('rbf', 1, 0.1), ('rbf', 1, 1), ('rbf', 1, 10), ('rbf', 1, 100),
                ('rbf', 5, 0.1), ('rbf', 5, 1), ('rbf', 5, 10), ('rbf', 5, 100),
    ('rbf', 1, 5), ('rbf', 50, 5), ('rbf', 100, 5), ('rbf', 1000,5))
x1_min, x2_min = np.min(X, axis=0) # 按类别计算
x1_max, x2_max = np.max(X, axis=0) # 按类别计算
print("x1_min: ",x1_min)
print("x2_min: ",x2_min)
print("x1_max: ",x1_max)
print("x2_max: ",x2_max)

np.min(X, axis=0)

x1_min:  4.9
x2_min:  2.0
x1_max:  7.9
x2_max:  3.8


0    4.9
1    2.0
dtype: float64

In [32]:
x1, x2 = np.mgrid[x1_min:x1_max:200j, x2_min:x2_max:200j]


[[4.9        4.9        4.9        ... 4.9        4.9        4.9       ]
 [4.91507538 4.91507538 4.91507538 ... 4.91507538 4.91507538 4.91507538]
 [4.93015075 4.93015075 4.93015075 ... 4.93015075 4.93015075 4.93015075]
 ...
 [7.86984925 7.86984925 7.86984925 ... 7.86984925 7.86984925 7.86984925]
 [7.88492462 7.88492462 7.88492462 ... 7.88492462 7.88492462 7.88492462]
 [7.9        7.9        7.9        ... 7.9        7.9        7.9       ]]


SyntaxError: invalid syntax (1709247285.py, line 1)